version: '3.8'

volumes:
  postgres-data:
  # Reuse Maven repository and NPM cache through volumes.
  # This caching is not ideal. While it keeps the caches between container rebuilds, it still means
  # that different dev containers get different volumes (the volume name is localized to the compose file),
  # leading to duplicated downloads. This can be mitigated through various means:
  # - using external volumes (have to be created by the developer once though)
  # - using a bind volume to a common dir (with the return of host specific paths)
  # - run a local artifact proxy
  maven-cache:
  npm-cache:


services:
  app:
    container_name: javadev
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in db container
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
        POSTGRES_HOSTNAME: postgresdb

    volumes:
      - ../..:/workspaces:cached
      - maven-cache:/home/vscode/.m2/repository
      - npm-cache:/home/.npm

      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  db:
    container_name: postgresdb
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in app container
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)